library('ggplot2')
library('reshape2')

advanced     <- read.csv('advanced.csv')
conservative <- read.csv('conservative.csv')
fencesitter  <- read.csv('fencesitter.csv')
malware      <- read.csv('malware.csv')
pus          <- read.csv('pus.csv')
unconcerned  <- read.csv('unconcerned.csv')

setEPS()
postscript("lin.eps")
lin <- merge(merge(merge(conservative, advanced), fencesitter), unconcerned)
d_lin <- melt(lin, id.vars=c(1))
p_lin <- ggplot(d_lin, aes(x=value, fill=variable)) + geom_histogram(binwidth=0.03) + scale_y_sqrt() 
update_labels(p_lin, list(x="Percentage of users apps meeting policy", y="User count", color="Policy"))
dev.off()

setEPS()
postscript("malware.eps")
bad <- merge(pus,malware)
d_bad <- melt(bad, id.vars=c(1))
p_bad <- ggplot(d_bad, aes(x=value, fill=variable)) + geom_histogram(binwidth=0.03) + scale_y_sqrt()
update_labels(p_bad, list(x="Percentage of users apps meeting policy", y="User count", color="Policy"))
dev.off()
